controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

article_create:
    path: /create-article
    controller: App\Controller\ArticleController::create